/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.MONAN;
import DTO.DTO_MonAn;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Ngoc Thang
 */
public class QuanLyMonAn extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyMonAn
     */
    DefaultTableModel model;
    JXTable tableMonAn; 
    ArrayList<DTO_MonAn> dsMonAn;
    int rowSelected = -1;
    public QuanLyMonAn() {
        initComponents();
        model = new DefaultTableModel();
        tableMonAn = new JXTable();
        model.addColumn("STT");
        model.addColumn("Mã Món Ăn");
        model.addColumn("Tên Món Ăn");
        model.addColumn("Đơn Giá");
        tableMonAn.setModel(model);
        
        LoadData();
        PaneMonAn.setViewportView(tableMonAn);
        tableMonAn.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt) {
                tableMonAn_MouseClicked(evt);
            }

            private void tableMonAn_MouseClicked(MouseEvent evt) {
                rowSelected = tableMonAn.getSelectedRow();
                txtMaMonAn.setText(dsMonAn.get(rowSelected).getMaMonAn());
                txtTenMonAn.setText(dsMonAn.get(rowSelected).getTenMonAn());
                txtDonGia.setText(String.valueOf(dsMonAn.get(rowSelected).getDonGia()));
            }
        });
    }

     public void LoadData(){
        if(dsMonAn != null)
            for (int i = 0; i < dsMonAn.size(); i++) {
                model.removeRow(0);
            }
        try {
            dsMonAn = MONAN.getAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không lấy danh sách món ăn!");
            return;
        }
        for (int i = 0; i < dsMonAn.size(); i++) {
            Vector vt = new Vector();
            vt.add(i + 1);
            vt.add(dsMonAn.get(i).getMaMonAn());
            vt.add(dsMonAn.get(i).getTenMonAn());
            vt.add(dsMonAn.get(i).getDonGia());
            model.addRow(vt);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTenMonAn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaMonAn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnThemMonAn = new javax.swing.JButton();
        btnSuaMonAn = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        PaneMonAn = new javax.swing.JScrollPane();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lý Món Ăn");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Món Ăn"));

        jLabel2.setText("Tên Món Ăn");

        txtMaMonAn.setEditable(false);

        jLabel3.setText("Đơn Giá");

        jLabel1.setText("Mã Món Ăn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenMonAn)
                    .addComponent(txtMaMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(txtDonGia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnThemMonAn.setText("Thêm Món Ăn");
        btnThemMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonAnActionPerformed(evt);
            }
        });

        btnSuaMonAn.setText("Sửa Món Ăn");
        btnSuaMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMonAnActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMonAn, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThemMonAn)
                        .addGap(28, 28, 28)
                        .addComponent(btnSuaMonAn)
                        .addGap(28, 28, 28)
                        .addComponent(btnNhapMoi)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMonAn)
                    .addComponent(btnSuaMonAn)
                    .addComponent(btnNhapMoi))
                .addGap(18, 18, 18)
                .addComponent(PaneMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonAnActionPerformed
        String MaMonAn = "", TenMonAn = "";
        double DonGia;
        MaMonAn = txtMaMonAn.getText();
        TenMonAn = txtTenMonAn.getText();
        if(TenMonAn.equals("") || txtDonGia.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try{
            DonGia = Double.parseDouble(txtDonGia.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đơn giá phải là số, vui lòng nhập lại!");
            return;
        }
        if(DonGia < 0){
            JOptionPane.showMessageDialog(null,"Đơn giá phải lớn hơn 0, vui lòng nhập lại!");
            return;
        }

        DTO_MonAn monAn = new DTO_MonAn(MaMonAn, TenMonAn, DonGia);
        try {
            MONAN.InsertNew(monAn);
            LoadData();
            JOptionPane.showMessageDialog(null,"Thêm món ăn thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể thêm món ăn \nMã món ăn đã tồn tại!");
            return;
        }
    }//GEN-LAST:event_btnThemMonAnActionPerformed

    private void btnSuaMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMonAnActionPerformed
        String MaMonAn = "", TenMonAn = "";
        double DonGia;
        MaMonAn = txtMaMonAn.getText();
        try{
            DTO_MonAn monan = MONAN.getById(MaMonAn);
            if(monan == null){
                JOptionPane.showMessageDialog(null,"Mã món ăn không tồn tại!\nVui lòng chọn 1 món ăn từ danh sách món");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể kết nối!");
            return;
        }
        TenMonAn = txtTenMonAn.getText();
        if(TenMonAn.equals("") || txtDonGia.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try{
            DonGia = Double.parseDouble(txtDonGia.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đơn giá phải là số, vui lòng nhập lại!");
            return;
        }
        if(DonGia < 0){
            JOptionPane.showMessageDialog(null,"Đơn giá phải lớn hơn 0, vui lòng nhập lại!");
            return;
        }

        DTO_MonAn monAn = new DTO_MonAn(MaMonAn, TenMonAn, DonGia);
        try {
            MONAN.Update(monAn);
            LoadData();
            JOptionPane.showMessageDialog(null,"Cập nhật món ăn thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể cập nhật món ăn!");
            return;
        }
    }//GEN-LAST:event_btnSuaMonAnActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        String MaMonAn = "";
        try {
            MaMonAn = MONAN.AutoGenerateID();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể kết nối!");
        }
        txtMaMonAn.setText(MaMonAn);
        txtTenMonAn.setText("");
        txtDonGia.setText("");
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String MaMonAn = "", TenMonAn = "";
        double DonGia;
        if(rowSelected < 0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn món ăn cần xóa!");
            return;
        }
        MaMonAn = tableMonAn.getValueAt(rowSelected, 1).toString();
        TenMonAn = tableMonAn.getValueAt(rowSelected, 2).toString();
        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa món " + TenMonAn, "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
                MONAN.Delete(MaMonAn);
                LoadData();
                JOptionPane.showMessageDialog(null,"Xóa món ăn thành công!");
                rowSelected = -1;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Không thể xóa món ăn!");
                return;
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PaneMonAn;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSuaMonAn;
    private javax.swing.JButton btnThemMonAn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaMonAn;
    private javax.swing.JTextField txtTenMonAn;
    // End of variables declaration//GEN-END:variables
}
