/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LOAIPHONG;
import DTO.DTO_LoaiPhong;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ngoc Thang
 */
public class QuanLyLoaiPhong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyLoaiPhong
     */
    DefaultTableModel model;
    JTable tableLoaiPhong; 
    ArrayList<DTO_LoaiPhong> dsLoaiPhong;
    int rowSelected = -1;
    public QuanLyLoaiPhong() {
        initComponents();
        model = new DefaultTableModel();
        tableLoaiPhong = new JTable();
        model.addColumn("STT");
        model.addColumn("Mã Loại Phòng");
        model.addColumn("Tên Loại Phòng");
        model.addColumn("Đơn Giá");
        model.addColumn("Mô Tả");
        tableLoaiPhong.setModel(model);
        
        LoadData();
        PaneLoaiPhong.setViewportView(tableLoaiPhong);
        tableLoaiPhong.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt) {
                tableMonAn_MouseClicked(evt);
            }

            private void tableMonAn_MouseClicked(MouseEvent evt) {
                rowSelected = tableLoaiPhong.getSelectedRow();
                txtMaLoaiPhong.setText(dsLoaiPhong.get(rowSelected).getMaLoaiPhong());
                txtTenLoaiPhong.setText(dsLoaiPhong.get(rowSelected).getTenLoaiPhong());
                txtDonGia.setText(String.valueOf(dsLoaiPhong.get(rowSelected).getDonGia()));
                txtMoTa.setText(dsLoaiPhong.get(rowSelected).getMoTa());
            }
        });
    }

    public void LoadData(){
        if(dsLoaiPhong != null)
            for (int i = 0; i < dsLoaiPhong.size(); i++) {
                model.removeRow(0);
            }
        try {
            dsLoaiPhong = LOAIPHONG.getAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không lấy danh sách loại phòng!");
            return;
        }
        for (int i = 0; i < dsLoaiPhong.size(); i++) {
            Vector vt = new Vector();
            vt.add(i + 1);
            vt.add(dsLoaiPhong.get(i).getMaLoaiPhong());
            vt.add(dsLoaiPhong.get(i).getTenLoaiPhong());
            vt.add(dsLoaiPhong.get(i).getDonGia());
            vt.add(dsLoaiPhong.get(i).getMoTa());
            model.addRow(vt);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTenLoaiPhong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaLoaiPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnThemLoaiPhong = new javax.swing.JButton();
        btnSuaLoaiPhong = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PaneLoaiPhong = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Loại Phòng"));

        jLabel2.setText("Tên Loại Phòng");

        txtMaLoaiPhong.setEditable(false);

        jLabel3.setText("Đơn Giá");

        jLabel1.setText("Mã Loại Phòng");

        jLabel4.setText("Mô Tả");

        txtMoTa.setColumns(1);
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(4);
        txtMoTa.setTabSize(6);
        jScrollPane1.setViewportView(txtMoTa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenLoaiPhong)
                    .addComponent(txtMaLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(txtDonGia))
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtTenLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        btnThemLoaiPhong.setText("Thêm Loại Phòng");
        btnThemLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiPhongActionPerformed(evt);
            }
        });

        btnSuaLoaiPhong.setText("Sửa Loại Phòng");
        btnSuaLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiPhongActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Loại Phòng"));

        jLabel5.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneLoaiPhong)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(PaneLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThemLoaiPhong)
                        .addGap(36, 36, 36)
                        .addComponent(btnSuaLoaiPhong)
                        .addGap(29, 29, 29)
                        .addComponent(btnNhapMoi)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemLoaiPhong)
                    .addComponent(btnSuaLoaiPhong)
                    .addComponent(btnNhapMoi))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiPhongActionPerformed
        String MaLoaiPhong = "", TenLoaiPhong = "", MoTa = "";
        double DonGia;
        MaLoaiPhong = txtMaLoaiPhong.getText();
        TenLoaiPhong = txtTenLoaiPhong.getText();
        MoTa = txtMoTa.getText();
        if(TenLoaiPhong.equals("") || txtDonGia.getText().equals("") || MoTa.equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try{
            DonGia = Double.parseDouble(txtDonGia.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đơn giá phải là số, vui lòng nhập lại!");
            return;
        }
        if(DonGia < 0){
            JOptionPane.showMessageDialog(null,"Đơn giá phải lớn hơn 0, vui lòng nhập lại!");
            return;
        }

        DTO_LoaiPhong loaiPhong = new DTO_LoaiPhong(MaLoaiPhong, TenLoaiPhong, DonGia, MoTa);
        try {
            LOAIPHONG.InsertNew(loaiPhong);
            LoadData();
            JOptionPane.showMessageDialog(null,"Thêm loại phòng thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể thêm loại phòng \nMã loại phòng đã tồn tại!");
            return;
        }
    }//GEN-LAST:event_btnThemLoaiPhongActionPerformed

    private void btnSuaLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiPhongActionPerformed
        String MaLoaiPhong = "", TenLoaiPhong = "", MoTa = "";
        double DonGia;
        MaLoaiPhong = txtMaLoaiPhong.getText();
        try{
            DTO_LoaiPhong loaiphong = LOAIPHONG.getById(MaLoaiPhong);
            if(loaiphong == null){
                JOptionPane.showMessageDialog(null,"Mã loại phòng không tồn tại!\nVui lòng chọn 1 loại phòng từ danh sách loại phòng");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể kết nối!");
            return;
        }
        TenLoaiPhong = txtTenLoaiPhong.getText();
        MoTa = txtMoTa.getText();
        if(TenLoaiPhong.equals("") || txtDonGia.getText().equals("") || MoTa.equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try{
            DonGia = Double.parseDouble(txtDonGia.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đơn giá phải là số, vui lòng nhập lại!");
            return;
        }
        if(DonGia < 0){
            JOptionPane.showMessageDialog(null,"Đơn giá phải lớn hơn 0, vui lòng nhập lại!");
            return;
        }

        DTO_LoaiPhong loaiPhong = new DTO_LoaiPhong(MaLoaiPhong, TenLoaiPhong, DonGia, MoTa);
        try {
            LOAIPHONG.Update(loaiPhong);
            LoadData();
            JOptionPane.showMessageDialog(null,"Cập nhật loại phòng thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể cập nhật loại phòng!");
            return;
        }
    }//GEN-LAST:event_btnSuaLoaiPhongActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        String MaLoaiPhong = "";
        try {
            MaLoaiPhong = LOAIPHONG.AutoGenerateID();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể kết nối!");
        }
        txtMaLoaiPhong.setText(MaLoaiPhong);
        txtTenLoaiPhong.setText("");
        txtDonGia.setText("");
        txtMoTa.setText("");
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String MaLoaiPhong = "", TenLoaiPhong = "";
        double DonGia;
        if(rowSelected < 0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn loại phòng cần xóa!");
            return;
        }
        MaLoaiPhong = tableLoaiPhong.getValueAt(rowSelected, 1).toString();
        TenLoaiPhong = tableLoaiPhong.getValueAt(rowSelected, 2).toString();
        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa loại phòng " + TenLoaiPhong, "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
                LOAIPHONG.Delete(MaLoaiPhong);
                LoadData();
                JOptionPane.showMessageDialog(null,"Xóa loại phòng thành công!");
                rowSelected = -1;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Không thể xóa loại phòng!");
                return;
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLoaiPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PaneLoaiPhong;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSuaLoaiPhong;
    private javax.swing.JButton btnThemLoaiPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaLoaiPhong;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
