/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DICHVU;
import DTO.DTO_DichVu;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ngoc Thang
 */
public class QuanLyDichVu extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyDichVu
     */
    DefaultTableModel model;
    JTable tableDichVu; 
    ArrayList<DTO_DichVu> dsDichVu;
    int rowSelected = -1;
    public QuanLyDichVu() {
        initComponents();
        model = new DefaultTableModel();
        tableDichVu = new JTable();
        model.addColumn("STT");
        model.addColumn("Mã Dịch Vụ");
        model.addColumn("Tên Dịch Vụ");
        model.addColumn("Đơn Giá");
        tableDichVu.setModel(model);
        
        LoadData();
        PaneDichVu.setViewportView(tableDichVu);
        tableDichVu.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt) {
                tableDichVu_MouseClicked(evt);
            }

            private void tableDichVu_MouseClicked(MouseEvent evt) {
                rowSelected = tableDichVu.getSelectedRow();
                txtMaDichVu.setText(dsDichVu.get(rowSelected).getMaDichVu());
                txtTenDichVu.setText(dsDichVu.get(rowSelected).getTenDichVu());
                txtDonGia.setText(String.valueOf(dsDichVu.get(rowSelected).getDonGia()));
            }
        });
    }

    public void LoadData(){
        if(dsDichVu != null)
            for (int i = 0; i < dsDichVu.size(); i++) {
                model.removeRow(0);
            }
        try {
            dsDichVu = DICHVU.getAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không lấy danh sách dịch vụ!");
            return;
        }
        for (int i = 0; i < dsDichVu.size(); i++) {
            Vector vt = new Vector();
            vt.add(i + 1);
            vt.add(dsDichVu.get(i).getMaDichVu());
            vt.add(dsDichVu.get(i).getTenDichVu());
            vt.add(dsDichVu.get(i).getDonGia());
            model.addRow(vt);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtMaDichVu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenDichVu = new javax.swing.JTextField();
        btnThemDV = new javax.swing.JButton();
        btnSuaDV = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PaneDichVu = new javax.swing.JScrollPane();

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Dịch Vụ"));

        txtMaDichVu.setEditable(false);

        jLabel3.setText("Đơn giá");

        jLabel1.setText("Mã Dịch Vụ");

        jLabel2.setText("Tên Dịch Vụ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaDichVu)
                    .addComponent(txtTenDichVu)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnThemDV.setText("Thêm Dịch Vụ");
        btnThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDVActionPerformed(evt);
            }
        });

        btnSuaDV.setText("Sửa Dịch Vụ");
        btnSuaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDVActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Dịch Vụ"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneDichVu)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemDV)
                                .addGap(58, 58, 58)
                                .addComponent(btnSuaDV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNhapMoi))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDV)
                    .addComponent(btnSuaDV)
                    .addComponent(btnNhapMoi))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDVActionPerformed
        String MaDichVu = "", TenDichVu = "";
        double DonGia;
        MaDichVu = txtMaDichVu.getText();
        TenDichVu = txtTenDichVu.getText();
        if(TenDichVu.equals("") || txtDonGia.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try{
            DonGia = Double.parseDouble(txtDonGia.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đơn giá phải là số, vui lòng nhập lại!");
            return;
        }
        if(DonGia < 0){
            JOptionPane.showMessageDialog(null,"Đơn giá phải lớn hơn 0, vui lòng nhập lại!");
            return;
        }
        
        DTO_DichVu monAn = new DTO_DichVu(MaDichVu, TenDichVu, DonGia);
        try {
            DICHVU.InsertNew(monAn);
            LoadData();
            JOptionPane.showMessageDialog(null,"Thêm dịch vụ thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể thêm dịch vụ \nMã dịch vụ đã tồn tại!");
            return;
        }
    }//GEN-LAST:event_btnThemDVActionPerformed

    private void btnSuaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDVActionPerformed
         String MaDichVu = "", TenDichVu = "";
        double DonGia;
        MaDichVu = txtMaDichVu.getText();
        TenDichVu = txtTenDichVu.getText();
        try{
            DTO_DichVu dichvu = DICHVU.getById(MaDichVu);
            if(dichvu == null){
                JOptionPane.showMessageDialog(null,"Mã dịch vụ không tồn tại!\nVui lòng chọn 1 dịch vụ từ danh sách");
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể kết nối!");
            return;
        }
        if(TenDichVu.equals("") || txtDonGia.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try{
            DonGia = Double.parseDouble(txtDonGia.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đơn giá phải là số, vui lòng nhập lại!");
            return;
        }
        if(DonGia < 0){
            JOptionPane.showMessageDialog(null,"Đơn giá phải lớn hơn 0, vui lòng nhập lại!");
            return;
        }
        
        DTO_DichVu monAn = new DTO_DichVu(MaDichVu, TenDichVu, DonGia);
        try {
            DICHVU.Update(monAn);
            LoadData();
            JOptionPane.showMessageDialog(null,"Cập nhật dịch vụ thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể cập nhật dịch vụ!");
            return;
        }
    }//GEN-LAST:event_btnSuaDVActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        String MaDichVu = "";
        try {
            MaDichVu = DICHVU.AutoGenerateID();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể kết nối!");
        }
        txtMaDichVu.setText(MaDichVu);
        txtTenDichVu.setText("");
        txtDonGia.setText("");
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String MaDichVu = "", TenDichVu = "";
        double DonGia;
        if(rowSelected < 0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn dịch vụ cần xóa!");
            return;
        }
        MaDichVu = tableDichVu.getValueAt(rowSelected, 1).toString();
        TenDichVu = tableDichVu.getValueAt(rowSelected, 2).toString();
        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa dịch vụ " + TenDichVu, "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
            DICHVU.Delete(MaDichVu);
            LoadData();
            JOptionPane.showMessageDialog(null,"Xóa dịch vụ thành công!");
            rowSelected = -1;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Không thể xóa dịch vụ!");
            return;
        }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PaneDichVu;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSuaDV;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDichVu;
    private javax.swing.JTextField txtTenDichVu;
    // End of variables declaration//GEN-END:variables
}
