/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.ScrollPane;
import java.awt.image.ImageObserver;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Ngoc Thang
 */
public class QuanLyNhaHangKhachSan extends javax.swing.JFrame {

    PhieuDatPhong fPhieuDat;
    PhieuThue fPhieuThue;
    ClosableTabbedPane fclose;
    QuanLyMonAn fMonAn;
    QuanLyKhachHang fKhachHang;
    QuanLyDichVu fDichVu;
    QuanLyLoaiPhong fLoaiPhong;
    QuanLyPhong fPhong;
    ClosableTabbedPane TabbedPaneMain;
    final String PRE = "<html><p style=\"text-align: right\">"; 
    final String POST = "</p></html>"; 
    public QuanLyNhaHangKhachSan() {
        initComponents();
        TabbedPaneMain = new ClosableTabbedPane();
        MainPane.setViewportView(TabbedPaneMain);
        if(fPhieuDat == null){
            fPhieuDat = new PhieuDatPhong();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        MainPane = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        menuItemMonAn = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuItemDichVu = new javax.swing.JMenuItem();
        menuItemLoaiPhong = new javax.swing.JMenuItem();
        menuItemPhong = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setForeground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setName("DesktopPane"); // NOI18N

        jToolBar2.setRollover(true);

        jDesktopPane1.setLayer(jToolBar2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(MainPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
            .addComponent(MainPane)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Quản Lý Khách Sạn");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Đặt Phòng");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Thuê Phòng");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        menuItemMonAn.setText("Quản Lý Món Ăn");
        menuItemMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMonAnActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemMonAn);

        jMenuItem3.setText("Quản Lý Khách Hàng");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem3);

        menuItemDichVu.setText("Quản Lý Dịch Vụ");
        menuItemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDichVuActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemDichVu);

        menuItemLoaiPhong.setText("Quản Lý Loại Phòng");
        menuItemLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoaiPhongActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemLoaiPhong);

        menuItemPhong.setText("Quản Lý Phòng");
        menuItemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPhongActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemPhong);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        if(fPhieuThue == null){
            fPhieuThue = new PhieuThue();
        }
        if(!TabbedPaneMain.isAncestorOf(fPhieuThue)){
            Icon icon = new ImageIcon(getClass().getResource("/Images/ThuePhong.png"));
            TabbedPaneMain.addTab(PRE + "Thuê Phòng" + POST, icon, fPhieuThue);
        }
        TabbedPaneMain.setSelectedComponent(fPhieuThue);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        
//        if(!TabbedPaneMain.isAncestorOf(fPhieuDat.getContentPane())){
//            Icon icon = new ImageIcon(getClass().getResource("/Images/Dat.png"));
//            TabbedPaneMain.addTab("Đặt Phòng", icon, fPhieuDat.getContentPane());   
//        }
//        TabbedPaneMain.setSelectedComponent(fPhieuDat.getContentPane());
        
        fPhieuDat.setVisible(true);
        
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void menuItemMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMonAnActionPerformed
        if(fMonAn == null){
            fMonAn = new QuanLyMonAn();
        }
        if(!TabbedPaneMain.isAncestorOf(fMonAn.getContentPane())){
            Icon icon = new ImageIcon(getClass().getResource("/Images/Dattiec.png"));
            TabbedPaneMain.addTab("Quản Lý Món Ăn", icon, fMonAn.getContentPane());   
            
        }
        TabbedPaneMain.setSelectedComponent(fMonAn.getContentPane());
    }//GEN-LAST:event_menuItemMonAnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(fKhachHang == null){
            fKhachHang = new QuanLyKhachHang();
        }
        //fKhachHang.setVisible(true);
        if(!TabbedPaneMain.isAncestorOf(fKhachHang.getContentPane())){
            Icon icon = new ImageIcon(getClass().getResource("/Images/khach.png"));
            TabbedPaneMain.addTab("Quản Lý Khách Hàng", icon, fKhachHang.getContentPane());   
        }
        TabbedPaneMain.setSelectedComponent(fKhachHang.getContentPane());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuItemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDichVuActionPerformed
        if(fDichVu == null){
            fDichVu = new QuanLyDichVu();
        }
        if(!TabbedPaneMain.isAncestorOf(fDichVu.getContentPane())){
            Icon icon = new ImageIcon(getClass().getResource("/Images/DichVu.png"));
            TabbedPaneMain.addTab("Quản Lý Dịch Vụ", icon, fDichVu.getContentPane());   
        }
        TabbedPaneMain.setSelectedComponent(fDichVu.getContentPane());
    }//GEN-LAST:event_menuItemDichVuActionPerformed

    private void menuItemLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoaiPhongActionPerformed
        if(fLoaiPhong == null){
            fLoaiPhong = new QuanLyLoaiPhong();
        }
        if(!TabbedPaneMain.isAncestorOf(fLoaiPhong.getContentPane())){
            Icon icon = new ImageIcon(getClass().getResource("/Images/LoaiPhong.png"));
            TabbedPaneMain.addTab("Quản Lý Loại Phòng", icon, fLoaiPhong.getContentPane());   
        }
        TabbedPaneMain.setSelectedComponent(fLoaiPhong.getContentPane());
        //fLoaiPhong.setVisible(true);
    }//GEN-LAST:event_menuItemLoaiPhongActionPerformed

    private void menuItemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPhongActionPerformed
        if(fPhong == null){
            fPhong = new QuanLyPhong();
        }
        //fPhong.setVisible(true);
        if(!TabbedPaneMain.isAncestorOf(fPhong.getContentPane())){
            Icon icon = new ImageIcon(getClass().getResource("/Images/quanlyphong.png"));
            TabbedPaneMain.addTab("Quản Lý Phòng", icon, fPhong.getContentPane());  
            
        }
        TabbedPaneMain.setSelectedComponent(fPhong.getContentPane());
    }//GEN-LAST:event_menuItemPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhaHangKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhaHangKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhaHangKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhaHangKhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhaHangKhachSan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane MainPane;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemDichVu;
    private javax.swing.JMenuItem menuItemLoaiPhong;
    private javax.swing.JMenuItem menuItemMonAn;
    private javax.swing.JMenuItem menuItemPhong;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
